### ISSUE TITLE
Would you be able to not be so sus?

### ISSUE THREAD

**Issue by XmYx** [AppleBotzz/ComfyUI_LLMVISION#6]
https://www.reddit.com/r/comfyui/comments/1dbls5n/psa_if_youve_used_the_comfyui_llmvision_node_from/

You really need to clear this fog around the wheels. Just publish the source code, and disclose the changes, including sending our browser history to.. (where?)

**Comment by rafstahelin** [comment]
What should users of this extension be doing at the moment to protect from hack? Virus scan? Or just not use it?

**Comment by XmYx** [comment]
I strongly suggest not using the node, furthermore, uninstalling the packages made by the creator with problematic license and potential malware inside them. Alternative safe nodes are available for comfyui that do use the original openai library, not a hacked, undisclosed source one.

**Comment by AppleBotzz** [comment]
See readme

**Comment by Qualzz** [comment]
> See readme

Nice attempt to cover your ass, but the commit history show this was deliberate, especially when you posted stuff like this. 
![image](https://github.com/AppleBotzz/ComfyUI_LLMVISION/assets/35169816/526fd8ae-02f9-45d9-8f16-fcb1829d58f3)
