### ISSUE TITLE
reopening the issue to give the creator a fighting chance.

### ISSUE THREAD

**Issue by XmYx** [AppleBotzz/ComfyUI_LLMVISION#7]
https://github.com/AppleBotzz/ComfyUI_LLMVISION/issues/6

**Comment by AppleBotzz** [comment]
As stated, see Readme. It explains all.

**Comment by XmYx** [comment]
as stated above, you are not the legitimate owner of the repository, nor the codebase, your actions - at this point - are considered to be illegal and malicious. reopening the issue.
